# Generated by Django 3.0.5 on 2020-04-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coice',
            new_name='Choice',
        ),
    ]
